[project]
name = "ai-prompt-history-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.2",
    "pytest>=8.4.2",
    "uvicorn>=0.36.0",
    "httpx>=0.27.0",
]
